Repository openshift/boilerplate, pull requests merged in 2024-07, with the labels that each got.

#368 Enable spellchecking in boilerplate repos
  boilerplate/openshift/golang-lint/ensure.sh
  boilerplate/openshift/golang-lint/golangci.yml
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
Labels: approved, lgtm

#369 Final final rvmo changes (v2)
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#370 Fix app-sre-build-push after switch to podman
  Makefile
  config/app-sre-build-push.sh
Labels: approved, lgtm

#371 Copy the node container auth file to allow pulling from registry.ci.openshift.org
  config/app-sre-build-push.sh
Labels: approved, lgtm

#372 Ignore exit code when checking if image exists
  config/app-sre-build-push.sh
Labels: approved, lgtm

#373 [OSD-13681] Added a prefix 'g' to handle leading zeroes in CSV version
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, tide/merge-method-squash, lgtm

#374 Adding additional reviewers
  OWNERS
Labels: approved, lgtm

#375 Add mmazur to reviewers/approvers
  OWNERS
Labels: approved, lgtm

#377 Update e2e harness image to Go 1.22
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh
Labels: approved, lgtm

#378 KONFLUX-3729: add containerfile for konflux
  config/Dockerfile.konflux
Labels: approved, lgtm, jira/valid-reference

#379 fix opm-build-push command to use python venv
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#380 fix the python usage in build-opm-catalog.sh too
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Labels: approved, lgtm

#381 add check that new version and previous version are not the same.
  boilerplate/openshift/golang-osd-operator/csv-generate/catalog-publish.sh
Labels: approved, lgtm

#383 KONFLUX-3729: set source-build true
  .tekton/image-pull-request.yaml
  .tekton/image-push.yaml
  config/Dockerfile.konflux
Labels: approved, lgtm, jira/valid-reference

#385 config: dl yq from gh releases
  config/build_image.sh
Labels: approved, lgtm
