Repository openshift/boilerplate, pull requests merged in 2024-10, with the labels that each got.

#416 Fix `safe.directory` CI issue
  boilerplate/_lib/boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/_lib/freeze-check
  boilerplate/update
  test/case/convention/openshift/golang-osd-operator/01-generated-files-checker
  test/case/convention/openshift/golang-osd-operator/02-make-boilerplate-freeze-check
  test/case/convention/openshift/golang-osd-operator/07-generate-crd-v1
  test/case/framework/01-bootstrap-update
  test/case/framework/02-nonexistent-convention
  test/case/framework/03-nexus-makefile-include
  test/case/framework/05-generate-commit
  test/lib.sh
Labels: approved, lgtm

#417 Build boilerplate images with Dockerfile primitives
  .tekton/image-pull-request.yaml
  .tekton/image-push.yaml
  Makefile
  README.md
  config/Dockerfile
  config/Dockerfile.appsre
  config/Dockerfile.konflux
  config/app-sre-build-push.sh
  config/build_image.sh
Labels: approved, lgtm

#418 update GH CLI version from 2.51.0 to 2.58.0
  config/Dockerfile
  config/Dockerfile.konflux
Labels: approved, tide/merge-method-squash, lgtm

#419 Update README with TL instructions for tagging CI image
  README.md
Labels: approved, lgtm

#413 .tekton/bundle-builder*: prune pipelines
  .tekton/bundle-builder-pull-request.yaml
  .tekton/bundle-builder-push.yaml
Labels: approved, lgtm

#421 .tekton/catalog-builder*: prune pipelines
  .tekton/catalog-builder-pull-request.yaml
  .tekton/catalog-builder-push.yaml
Labels: approved, lgtm

#420 Reconcile RHEL versions and update build paths.
  README.md
  config/Dockerfile
  config/app-sre-build-push.sh
Labels: approved, tide/merge-method-squash, lgtm

#426 Update osde2e image repo in test-harness-template.yml
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
Labels: approved, lgtm

#430 golang-osd-operator-osde2e: alter base image
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh
Labels: approved, lgtm

#428 🫡 Remove mjlshen and arjunrn from approvers
  OWNERS
Labels: approved, lgtm

#432 update security team roster
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
Labels: approved, lgtm

#436 Removing NautiluX from TL alias
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
Labels: approved, lgtm

#438 Check if LATEST_IMAGE_TAG is set before getting latest tag
  boilerplate/update
Labels: approved, lgtm

#439 fix: allow custom clone commands for updating
  boilerplate/update
Labels: approved, lgtm

#440 fix: quotes preventing expansion
  boilerplate/update
Labels: approved, lgtm

#441 OWNERS: add self to reviewers
  OWNERS
Labels: approved, lgtm

#443 KONFLUX-3729: swap over image and rm build script
  .tekton/image-pull-request.yaml
  .tekton/image-push.yaml
  Makefile
  README.md
  config/Dockerfile
  config/Dockerfile.konflux
  config/app-sre-build-push.sh
Labels: approved, lgtm, jira/valid-reference

#444 KONFLUX-3729: swap to new base image on update
  boilerplate/openshift/golang-osd-operator/update
Labels: approved, lgtm, jira/valid-reference
