Repository openshift/boilerplate, pull requests merged in 2025-07, with the labels that each got.

#564 SDCICD-1593 make e2e convention independent of operator convention
  boilerplate/openshift/golang-osd-e2e/OWNERS
  boilerplate/openshift/golang-osd-e2e/README.md
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
  boilerplate/openshift/golang-osd-e2e/project.mk
  boilerplate/openshift/golang-osd-e2e/standard.mk
  boilerplate/openshift/golang-osd-e2e/update
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-image-build-push.sh
Labels: approved, lgtm

#567 update srep-infra-cicd team
  OWNERS_ALIASES
Labels: approved, lgtm

#570 SDCICD-1585 Add "CAD_PAGERDUTY_ROUTING_KEY" env variable to e2e bp template
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
Labels: approved, lgtm

#575 SREP-1170: Create Tekton Pipeline to run `pr-check` in Konflux
  .tekton/boilerplate-master-pr-check.yaml
  .tekton/image-pull-request.yaml
  boilerplate/_lib/boilerplate-commit
  boilerplate/update
  test/case/convention/openshift/golang-osd-operator/01-generated-files-checker
  test/case/convention/openshift/golang-osd-operator/07-generate-crd-v1
  test/case/framework/01-bootstrap-update
  test/case/framework/02-nonexistent-convention
  test/case/framework/03-nexus-makefile-include
  test/lib.sh
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#580 SREP-1170: Ensure `make pr-check` works on macOS and in Konflux
  .tekton/boilerplate-master-pr-check.yaml
  boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
  boilerplate/openshift/golang-osd-operator/rvmo-bundle.sh
  config/tag-check.sh
  test/case/convention/openshift/golang-osd-operator/05-build-olm-catalog
  test/driver
  test/lib.sh
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#584 SREP-1227: Run `make pr-check` in a container via `make container-pr-check`
  Makefile
  README.md
Labels: approved, lgtm, jira/valid-reference

#585 SDCICD-1592 set progressive delivery e2e template to claim from cluster reserve
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
Labels: approved, lgtm

#582 SREP-144: Switch to UBI9 and install Go 1.24
  boilerplate/openshift/golang-osd-e2e/update
  boilerplate/openshift/golang-osd-operator/Dockerfile.olm-registry
  config/Dockerfile
  test/projects/file-generate/build/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#590 pipelines/catalog-builder: drop prefetch-dependencies
  pipelines/catalog-builder/pipeline.yaml
Labels: approved, lgtm

#586 Update Owners Aliases for Team FedRAMP
  OWNERS_ALIASES
Labels: approved, lgtm

#592 Add CLAUDE.md for AI development assistance
  CLAUDE.md
Labels: approved, lgtm
