Repository openshift/boilerplate, pull requests merged in 2025-04, with the labels that each got.

#514 SDCICD-1521: set --only-health-check-nodes for PD
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
Labels: approved, lgtm, jira/valid-reference

#515 fix: match operator name var more strictly
  boilerplate/openshift/golang-osd-operator-osde2e/update
Labels: approved, lgtm

#516 OSD-29374: Drop unsupported `strictfipsruntime` GOEXPERIMENT for Go 1.23
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#517 OSD-29370: Configure `HOME` for golang-lint and golang-codecov boilerplate conventions
  boilerplate/openshift/golang-codecov/standard.mk
  boilerplate/openshift/golang-lint/standard.mk
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#518 Bump golangci-lint to v2
  boilerplate/openshift/golang-lint/ensure.sh
  boilerplate/openshift/golang-lint/golangci.yml
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
  config/Dockerfile
Labels: approved, tide/merge-method-squash, lgtm

#522 Only return early for empty TESTTARGETS when required
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#520 Handle `GOCACHE` better in CI environments
  README.md
  boilerplate/openshift/golang-codecov/standard.mk
  boilerplate/openshift/golang-lint/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/osd-container-image/standard.mk
Labels: approved, tide/merge-method-squash, lgtm

#524 Add GOENV missing from go-test target
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#525 Utilize custom `GOCACHE` for `op-generate` target
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#523 OSD-29557: Remove the `GOLANGCI_OPTIONAL_CONFIG` option, which is unused
  boilerplate/openshift/golang-lint/README.md
  boilerplate/openshift/golang-lint/standard.mk
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm, jira/valid-reference

#526 OSD-29553: Set `XDG_CACHE_HOME` to avoid hackery with `GOCACHE`
  boilerplate/openshift/golang-codecov/standard.mk
  boilerplate/openshift/golang-lint/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/osd-container-image/standard.mk
  config/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#527 SDCICD-1472 skip must-gather and destroy cluster steps in operator e2e suite
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
Labels: approved, lgtm

#531 Fix usage of `PWD` for `op-generate` target in `goland-osd-operator`
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#529 Clean up job output when running `ensure.sh`
  boilerplate/openshift/golang-lint/ensure.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
Labels: approved, lgtm

#530 Add readme to e2e scaffolding; Update osde2e convention readme
  boilerplate/openshift/golang-osd-operator-osde2e/README.md
  boilerplate/openshift/golang-osd-operator-osde2e/update
Labels: approved, lgtm

#533 update owners
  OWNERS
Labels: approved, lgtm
